import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    name: 'English',
    flag: '🇬🇧',
    navbar: { home: 'Home', search: 'Search', dashboard: 'Dashboard' },
    hero: {
      badge: 'AI-Powered Wish Matching Platform',
      title: 'Got a wish? WishPal makes it happen.',
      subtitle: 'powered by AI and 100% free. Try it now',
      formula: "It's simple: Post your wish, our AI Bots work 24/7, and you receive precise leads and tailored advice.",
      cta: { free: 'It is Free, start now', makeWish: 'Make a Wish', explore: 'Explore Wishes', exploreWishpads: 'Explore WishPads', seeBenefits: 'See Benefits' },
      search: { placeholder: "Search wishes... e.g., 'house cleaning', 'web developer job'", button: 'Search' },
    },
    ticker: {
      mostSuccessful: 'Most successful wishes this week:',
      jobsFound: 'Jobs found',
      productsBought: 'Products bought',
      usersAdvised: 'Users advised for free',
      trending: 'Trending:',
      wishesFulfilled: 'Wishes fulfilled',
      activeWishes: 'Active wishes',
      beingPosted: 'Being posted now',
    },
    stats: {
      liveNow: 'Live Now',
      wishesLive: 'Wishes Live',
      closedThisWeek: 'Closed This Week',
      beingPostedNow: 'Being Posted Now',
      updatingRealTime: 'Updating in real-time',
    },
    banner: {
      wishesLiveNow: 'Wishes Live Now',
      closedThisWeek: 'Closed This Week',
      jobsFound: 'Jobs Found',
      productsBought: 'Products Bought',
    },
    noticeBoard: {
      title: 'Notice Board',
      viewAll: 'View all',
      empty: 'No wishes posted yet. Be the first!',
    },
    map: {
      title: 'WishPad Map',
      allCountries: 'All Countries',
      matches: 'matches',
      viewPage: 'View Page',
    },
    closingSoon: {
      title: 'Closing Soon',
      empty: 'No wishes closing soon',
      lastDay: 'Last day!',
    },
    topWishpads: {
      title: 'Explore Top WishPads',
      subtitle: 'Discover businesses and service providers ready to fulfill your wishes worldwide',
      empty: 'No WishPads registered yet. Be the first!',
      register: 'Register as WishPad',
      matches: 'matches',
    },
    testimonials: {
      title: 'Success Stories',
      subtitle: 'Real people, real results — powered by WishPal',
      verified: 'Verified',
    },
    features: {
      title: 'Why We All Need WishPal',
      subtitle: 'The platform that connects wishes with opportunities',
      individuals: {
        title: 'For Ordinary Users (Individuals)',
        benefit1: 'Instant Access to Solutions',
        benefit1Desc: 'Post any wish — big or small — and our AI Bots immediately start searching 24/7 for practical solutions, whether it’s finding a job, affordable housing, medical advice, travel deals, or personal development opportunities.',
        benefit2: 'Personalized Advice & Leads',
        benefit2Desc: 'Receive tailored recommendations, direct contacts, and relevant opportunities without spending hours searching yourself.',
        benefit3: 'Problem Solver',
        benefit3Desc: 'From fixing a leaking roof to advancing your career or finding the perfect school for your child — your wish gets constant attention until solutions arrive.',
        benefit4: 'Free & Stress-Free',
        benefit4Desc: 'No need for expensive consultants or time-consuming research. Just post and let the AI work for you.',
        benefit5: 'Save Costs when Buying',
        benefit5Desc: 'Get matched with competitive offers for products and services you need — insurance, electronics, household services, and more.',
        more: 'More Benefits →',
      },
      businesses: {
        title: 'For Businesses',
        benefit1: 'Revenue Generator',
        benefit1Desc: 'Turn customer wishes into real sales. Businesses get matched with people actively seeking their products or services — warm leads instead of cold outreach.',
        benefit2: 'Cost-Saving Tool',
        benefit2Desc: 'Dramatically reduce marketing spend. Instead of running expensive ads, get connected directly to ready-to-buy customers through wish-based matching.',
        benefit3: 'Market Intelligence',
        benefit3Desc: 'Receive AI-powered insights on what customers truly want right now, helping you adjust offerings, pricing, and strategy in real time.',
        benefit4: '24/7 Lead Generation',
        benefit4Desc: 'While you sleep, our AI Bots are finding and qualifying new business opportunities for you.',
        benefit5: 'Save Costs when Buying',
        benefit5Desc: 'Reduce procurement and operational costs by getting matched with the best suppliers, vendors, and service providers through AI-driven negotiation and bulk buying insights.',
        more: 'More Benefits →',
      },
      ngos: {
        title: 'Non-Profit Organisations (NGOs)',
        benefit1: 'Impact Amplifier',
        benefit1Desc: 'Post wishes on behalf of communities and get matched with donors, volunteers, partners, and resources to amplify your impact.',
        benefit2: 'Resource Mobilization',
        benefit2Desc: 'Quickly find funding, expertise, equipment, or collaborators without traditional lengthy proposal processes.',
        benefit3: 'Problem Solving at Scale',
        benefit3Desc: 'Address social challenges faster by leveraging AI to connect needs with global opportunities and willing helpers.',
        benefit4: 'Data-Driven Insights',
        benefit4Desc: 'Gain valuable intelligence on community needs and trends to strengthen proposals and improve program effectiveness.',
        benefit5: 'Save Costs when Buying',
        benefit5Desc: 'Stretch your budget further by getting AI-matched with discounted supplies, pro-bono services, donor-partnered procurement, and cost-effective solutions tailored for non-profits.',
        more: 'More Benefits →',
      },
    },
    tagline: {
      title: 'WishPal: The only tool for all your need all times',
      subtitle: 'Your wishes, matched by AI. Every time, every need.',
      cta: 'It is Free, start now',
    },
    benefitsPage: {
      individuals: {
        title: 'For Ordinary Users (Individuals)',
        subtitle: 'Empowering everyday people with AI-driven wish fulfillment — free, fast, and effective.',
        hero: 'WishPal gives individuals a powerful platform to get things done without the hassle. Post a wish, and let AI work around the clock to connect you with the right people, services, and opportunities.',
        benefit1: {
          title: 'Instant Access to Solutions',
          desc: 'Post any wish — big or small — and our AI Bots immediately start searching 24/7 for practical solutions, whether it\'s finding a job, affordable housing, medical advice, travel deals, or personal development opportunities. No more endless Googling or asking around.',
        },
        benefit2: {
          title: 'Personalized Advice & Leads',
          desc: 'Receive tailored recommendations based on your specific needs, location, and preferences. Our AI analyzes your wish and matches you with the most relevant providers, opportunities, and solutions — saving you hours of research.',
        },
        benefit3: {
          title: 'Problem Solver',
          desc: 'From fixing a leaking roof to advancing your career or finding the perfect school for your child — your wish gets constant attention until solutions arrive. The AI persists, learns, and refines matches over time to ensure you get results.',
        },
        benefit4: {
          title: 'Free & Stress-Free',
          desc: 'No need for expensive consultants or time-consuming research. Just post and let the AI work for you. The platform is free for individuals, with optional premium features for those who want even faster results.',
        },
        benefit5: {
          title: 'Always Save Costs when Buying',
          desc: 'Get matched with competitive offers for products and services you need. Whether it\'s insurance, electronics, or household services — our AI finds you the best value deals so you always save money.',
        },
        benefit6: {
          title: 'Be Informed on Anything',
          desc: 'Stay updated with AI-curated information relevant to your wishes and interests. Get news, tips, and insights tailored to what matters to you — from market trends to educational resources.',
        },
        benefit7: {
          title: 'Generate Quick Cash',
          desc: 'Have a skill or asset? Post what you can offer and get matched with people who need it. Turn your talents, spare time, or unused items into extra income fast.',
        },
        summary: 'For individuals, WishPal is your personal assistant, researcher, matchmaker, and problem solver — all in one. It puts the power of AI to work for you, every day, for free.',
      },
      businesses: {
        title: 'For Businesses',
        subtitle: 'Transform customer wishes into revenue with AI-powered lead generation and market intelligence.',
        hero: 'WishPal gives businesses a direct line to customers who are actively seeking what you offer. No cold outreach, no wasted ad spend — just warm, qualified leads delivered to your doorstep by AI.',
        benefit1: {
          title: 'Revenue Generator',
          desc: 'Turn customer wishes into real sales. Businesses get matched with people actively seeking their products or services — warm leads instead of cold outreach. The AI qualifies each match based on intent, budget, and proximity, so every lead counts.',
        },
        benefit2: {
          title: 'Cost-Saving Tool',
          desc: 'Dramatically reduce marketing spend. Instead of running expensive ads with uncertain ROI, get connected directly to ready-to-buy customers through wish-based matching. Pay only for results, not impressions.',
        },
        benefit3: {
          title: 'Market Intelligence',
          desc: 'Receive AI-powered insights on what customers truly want right now, helping you adjust offerings, pricing, and strategy in real time. Understand demand patterns, seasonal trends, and emerging needs in your industry.',
        },
        benefit4: {
          title: '24/7 Lead Generation',
          desc: 'While you sleep, our AI Bots are finding and qualifying new business opportunities for you. Wake up to a pipeline of warm leads matched to your business — never miss a sales opportunity again.',
        },
        benefit5: {
          title: 'Build Your WishPad Page',
          desc: 'Create a professional business page with your logo, description, social links, and location. Customers can discover you on the WishPad map, browse your offerings, and connect directly through the platform.',
        },
        benefit6: {
          title: 'Customer Insights Dashboard',
          desc: 'Access detailed analytics on who is wishing for what in your area. Understand customer demographics, popular categories, and conversion metrics to fine-tune your business strategy.',
        },
        benefit7: {
          title: 'Brand Visibility & Trust',
          desc: 'Get listed among verified WishPads with customer ratings and success metrics. Build trust through transparency and let your matched results speak for themselves.',
        },
        summary: 'For businesses, WishPad is the most efficient customer acquisition tool you will ever use. Stop chasing customers — let them come to you.',
      },
      ngos: {
        title: 'For Non-Profit Organisations & NGOs',
        subtitle: 'Amplify your impact by connecting community needs with global resources and willing helpers.',
        hero: 'WishPal provides NGOs and non-profits with a powerful platform to post community needs, mobilize resources, and connect with donors, volunteers, and partners worldwide — all powered by intelligent AI matching.',
        benefit1: {
          title: 'Impact Amplifier',
          desc: 'Post wishes on behalf of communities and get matched with donors, volunteers, partners, and resources to amplify your impact. Whether it\'s school supplies, medical equipment, or community infrastructure — tell us what you need and let AI find the support.',
        },
        benefit2: {
          title: 'Resource Mobilization',
          desc: 'Quickly find funding, expertise, equipment, or collaborators without traditional lengthy proposal processes. The AI identifies potential donors, grant opportunities, and in-kind contributors who align with your mission.',
        },
        benefit3: {
          title: 'Problem Solving at Scale',
          desc: 'Address social challenges faster by leveraging AI to connect needs with global opportunities and willing helpers. From disaster relief to long-term development projects — scale your impact beyond traditional networks.',
        },
        benefit4: {
          title: 'Data-Driven Insights',
          desc: 'Gain valuable intelligence on community needs and trends to strengthen proposals and improve program effectiveness. Use real-time wish data to demonstrate need, justify funding, and measure outcomes.',
        },
        benefit5: {
          title: 'Volunteer Matching',
          desc: 'Find skilled volunteers who want to contribute their time and expertise to your cause. The AI matches volunteer profiles with specific NGO needs — from pro-bono legal advice to teaching and healthcare.',
        },
        benefit6: {
          title: 'Partnership Discovery',
          desc: 'Identify and connect with other NGOs, government agencies, and corporate partners working in similar spaces. Collaborate on shared goals, co-author proposals, and avoid duplication of efforts.',
        },
        benefit7: {
          title: 'Transparent Impact Reporting',
          desc: 'Track and showcase every wish fulfilled, resource mobilized, and life impacted. Build donor confidence with transparent, data-backed impact reports generated automatically by the platform.',
        },
        summary: 'For NGOs, WishPal is a force multiplier. Do more with less, reach further with AI, and turn every wish into a measurable outcome.',
      },
    },
    footer: {
      description: 'Your wishes, matched by AI. We connect you with the right people to fulfill your wishes.',
      platform: 'Platform',
      browseWishes: 'Browse Wishes',
      joinWishMate: 'Join as WishMate',
      joinWishPad: 'Join as WishPad',
      support: 'Support',
      faq: 'FAQ',
      contactUs: 'Contact Us',
      privacyPolicy: 'Privacy Policy',
      legal: 'Legal',
      termsOfService: 'Terms of Service',
      cookiePolicy: 'Cookie Policy',
      allRightsReserved: 'All rights reserved.',
    },
    daysLeft: '{days}d left',
    today: 'Today',
  },
  fr: {
    name: 'Français',
    flag: '🇫🇷',
    hero: {
      badge: 'Plateforme de correspondance de souhaits par IA',
      title: 'Un souhait ? WishPal le réalise —',
      subtitle: 'propulsé par l\'IA et 100% gratuit. Essayez maintenant',
      formula: 'Votre Souhait + WishPal = Votre Solution',
      cta: { free: 'C\'est gratuit, commencez maintenant', makeWish: 'Faire un Souhait', explore: 'Explorer les Souhaits' },
      search: { placeholder: 'Rechercher des souhaits... ex: "ménage", "emploi développeur"', button: 'Rechercher' },
    },
    ticker: {
      mostSuccessful: 'Souhaits les plus réussis cette semaine :',
      jobsFound: 'Emplois trouvés',
      productsBought: 'Produits achetés',
      usersAdvised: 'Utilisateurs conseillés gratuitement',
      trending: 'Tendances :',
      wishesFulfilled: 'Souhaits réalisés',
      activeWishes: 'Souhaits actifs',
      beingPosted: 'Publiés maintenant',
    },
    stats: {
      liveNow: 'En Direct',
      wishesLive: 'Souhaits en Direct',
      closedThisWeek: 'Clos Cette Semaine',
      beingPostedNow: 'Publiés Maintenant',
      updatingRealTime: 'Mise à jour en temps réel',
    },
    banner: {
      wishesLiveNow: 'Souhaits en Direct',
      closedThisWeek: 'Clos Cette Semaine',
      jobsFound: 'Emplois Trouvés',
      productsBought: 'Produits Achetés',
    },
    noticeBoard: {
      title: 'Tableau d\'Affichage',
      viewAll: 'Voir tout',
      empty: 'Aucun souhait publié. Soyez le premier !',
    },
    map: {
      title: 'Carte WishPad',
      allCountries: 'Tous les Pays',
      matches: 'correspondances',
      viewPage: 'Voir la Page',
    },
    closingSoon: {
      title: 'Bientôt Fermé',
      empty: 'Aucun souhait ne ferme bientôt',
      lastDay: 'Dernier jour !',
    },
    topWishpads: {
      title: 'Découvrir les Meilleurs WishPads',
      subtitle: 'Découvrez des entreprises et prestataires prêts à réaliser vos souhaits dans le monde entier',
      empty: 'Aucun WishPad inscrit. Soyez le premier !',
      register: 'S\'inscrire comme WishPad',
      matches: 'correspondances',
    },
    testimonials: {
      title: 'Histoires de Réussite',
      subtitle: 'Des vraies personnes, des vrais résultats — propulsés par WishPal',
      verified: 'Vérifié',
    },
    features: {
      title: 'Pourquoi Nous Avons Tous Besoin de WishPal',
      subtitle: 'La plateforme qui connecte les souhaits aux opportunités',
      revenue: { title: 'Générateur de Revenus', desc: 'Transformez les souhaits en revenus. Les entreprises sont mises en relation avec des clients recherchant activement leurs services.' },
      costSaving: { title: 'Outil d\'Économie', desc: 'Économisez en trouvant exactement ce qu\'il vous faut grâce à la correspondance basée sur les souhaits. Pas de publicités coûteuses.' },
      informative: { title: 'Informatif', desc: 'Informations basées sur l\'IA pour chaque souhait. Correspondance intelligente et recommandations data-driven.' },
      problemSolving: { title: 'Résolution de Problèmes', desc: 'Un problème ? Publiez un souhait et laissez notre IA vous trouver la solution parfaite.' },
    },
    tagline: {
      title: 'WishPal : Le seul outil pour tous vos besoins, à tout moment',
      subtitle: 'Vos souhaits, associés par IA. À chaque fois, pour chaque besoin.',
      cta: 'C\'est gratuit, commencez maintenant',
    },
    footer: {
      description: 'Vos souhaits, associés par IA. Nous vous connectons avec les bonnes personnes pour réaliser vos souhaits.',
      platform: 'Plateforme',
      browseWishes: 'Parcourir les Souhaits',
      joinWishMate: 'Rejoindre comme WishMate',
      joinWishPad: 'Rejoindre comme WishPad',
      support: 'Support',
      faq: 'FAQ',
      contactUs: 'Nous Contacter',
      privacyPolicy: 'Politique de Confidentialité',
      legal: 'Mentions Légales',
      termsOfService: 'Conditions d\'Utilisation',
      cookiePolicy: 'Politique des Cookies',
      allRightsReserved: 'Tous droits réservés.',
    },
    daysLeft: 'encore {days}j',
    today: 'Aujourd\'hui',
  },
  es: {
    name: 'Español',
    flag: '🇪🇸',
    hero: {
      badge: 'Plataforma de coincidencia de deseos con IA',
      title: '¿Un deseo? WishPal lo hace realidad —',
      subtitle: 'impulsado por IA y 100% gratis. Pruébalo ahora',
      formula: 'Tu Deseo + WishPal = Tu Solución',
      cta: { free: 'Es gratis, empieza ahora', makeWish: 'Pedir un Deseo', explore: 'Explorar Deseos' },
      search: { placeholder: 'Buscar deseos... ej: "limpieza", "trabajo desarrollador"', button: 'Buscar' },
    },
    ticker: {
      mostSuccessful: 'Deseos más exitosos esta semana:',
      jobsFound: 'Empleos encontrados',
      productsBought: 'Productos comprados',
      usersAdvised: 'Usuarios asesorados gratis',
      trending: 'Tendencias:',
      wishesFulfilled: 'Deseos cumplidos',
      activeWishes: 'Deseos activos',
      beingPosted: 'Publicándose ahora',
    },
    stats: {
      liveNow: 'En Vivo',
      wishesLive: 'Deseos en Vivo',
      closedThisWeek: 'Cerrados Esta Semana',
      beingPostedNow: 'Publicándose Ahora',
      updatingRealTime: 'Actualizando en tiempo real',
    },
    banner: {
      wishesLiveNow: 'Deseos en Vivo',
      closedThisWeek: 'Cerrados Esta Semana',
      jobsFound: 'Empleos Encontrados',
      productsBought: 'Productos Comprados',
    },
    noticeBoard: {
      title: 'Tablón de Anuncios',
      viewAll: 'Ver todo',
      empty: 'No hay deseos publicados. ¡Sé el primero!',
    },
    map: {
      title: 'Mapa WishPad',
      allCountries: 'Todos los Países',
      matches: 'coincidencias',
      viewPage: 'Ver Página',
    },
    closingSoon: {
      title: 'Próximo a Cerrar',
      empty: 'No hay deseos por cerrar pronto',
      lastDay: '¡Último día!',
    },
    topWishpads: {
      title: 'Explorar los Mejores WishPads',
      subtitle: 'Descubre empresas y proveedores listos para cumplir tus deseos en todo el mundo',
      empty: 'No hay WishPads registrados. ¡Sé el primero!',
      register: 'Registrarse como WishPad',
      matches: 'coincidencias',
    },
    testimonials: {
      title: 'Historias de Éxito',
      subtitle: 'Gente real, resultados reales — impulsados por WishPal',
      verified: 'Verificado',
    },
    features: {
      title: 'Por Qué Todos Necesitamos WishPal',
      subtitle: 'La plataforma que conecta deseos con oportunidades',
      revenue: { title: 'Generador de Ingresos', desc: 'Convierte deseos en ingresos. Las empresas se conectan con clientes que buscan activamente sus servicios.' },
      costSaving: { title: 'Herramienta de Ahorro', desc: 'Ahorra dinero encontrando exactamente lo que necesitas. Sin anuncios caros ni comisiones de intermediarios.' },
      informative: { title: 'Informativo', desc: 'Información impulsada por IA para cada deseo. Coincidencias inteligentes y recomendaciones basadas en datos.' },
      problemSolving: { title: 'Solución de Problemas', desc: '¿Tienes un problema? Publica un deseo y deja que nuestra IA te encuentre la solución perfecta.' },
    },
    tagline: {
      title: 'WishPal: La única herramienta para todas tus necesidades en todo momento',
      subtitle: 'Tus deseos, emparejados por IA. Cada vez, cada necesidad.',
      cta: 'Es gratis, empieza ahora',
    },
    footer: {
      description: 'Tus deseos, emparejados por IA. Te conectamos con las personas adecuadas para cumplir tus deseos.',
      platform: 'Plataforma',
      browseWishes: 'Explorar Deseos',
      joinWishMate: 'Únete como WishMate',
      joinWishPad: 'Únete como WishPad',
      support: 'Soporte',
      faq: 'FAQ',
      contactUs: 'Contáctanos',
      privacyPolicy: 'Política de Privacidad',
      legal: 'Legal',
      termsOfService: 'Términos de Servicio',
      cookiePolicy: 'Política de Cookies',
      allRightsReserved: 'Todos los derechos reservados.',
    },
    daysLeft: '{days}d restantes',
    today: 'Hoy',
  },
  zh: {
    name: '中文',
    flag: '🇨🇳',
    hero: {
      badge: 'AI智能愿望匹配平台',
      title: '有愿望？WishPal帮你实现 —',
      subtitle: 'AI驱动，100%免费。立即尝试',
      formula: '你的愿望 + WishPal = 你的解决方案',
      cta: { free: '免费，立即开始', makeWish: '许个愿望', explore: '浏览愿望' },
      search: { placeholder: '搜索愿望... 例如："家政清洁"、"网页开发工作"', button: '搜索' },
    },
    ticker: {
      mostSuccessful: '本周最成功的愿望：',
      jobsFound: '找到的工作',
      productsBought: '购买的产品',
      usersAdvised: '免费咨询的用户',
      trending: '热门：',
      wishesFulfilled: '已实现的愿望',
      activeWishes: '活跃愿望',
      beingPosted: '正在发布',
    },
    stats: {
      liveNow: '实时',
      wishesLive: '实时愿望',
      closedThisWeek: '本周已关闭',
      beingPostedNow: '正在发布',
      updatingRealTime: '实时更新',
    },
    banner: {
      wishesLiveNow: '实时愿望',
      closedThisWeek: '本周已关闭',
      jobsFound: '找到的工作',
      productsBought: '购买的产品',
    },
    noticeBoard: {
      title: '公告板',
      viewAll: '查看全部',
      empty: '还没有发布的愿望。成为第一个！',
    },
    map: {
      title: 'WishPad地图',
      allCountries: '所有国家',
      matches: '匹配',
      viewPage: '查看页面',
    },
    closingSoon: {
      title: '即将关闭',
      empty: '没有即将关闭的愿望',
      lastDay: '最后一天！',
    },
    topWishpads: {
      title: '探索热门WishPad',
      subtitle: '发现全球准备好实现你愿望的企业和服务提供商',
      empty: '还没有注册的WishPad。成为第一个！',
      register: '注册为WishPad',
      matches: '匹配',
    },
    testimonials: {
      title: '成功故事',
      subtitle: '真实的人，真实的结果 — 由WishPal驱动',
      verified: '已验证',
    },
    features: {
      title: '为什么我们都需要WishPal',
      subtitle: '连接愿望与机遇的平台',
      revenue: { title: '创收工具', desc: '将愿望转化为收入。企业与积极寻求服务的客户精准匹配。' },
      costSaving: { title: '省钱工具', desc: '通过基于愿望的匹配找到你真正需要的东西。没有昂贵的广告或中间商费用。' },
      informative: { title: '信息丰富', desc: '每个愿望的AI驱动洞察。智能匹配、市场情报和数据驱动推荐。' },
      problemSolving: { title: '解决问题', desc: '有问题？发布愿望，让我们的AI为你找到完美解决方案。从家庭维修到职业发展。' },
    },
    tagline: {
      title: 'WishPal：满足你所有需求的唯一工具',
      subtitle: '你的愿望，由AI匹配。每次都有求必应。',
      cta: '免费，立即开始',
    },
    footer: {
      description: '你的愿望，由AI匹配。我们为你连接合适的人来实现你的愿望。',
      platform: '平台',
      browseWishes: '浏览愿望',
      joinWishMate: '加入成为WishMate',
      joinWishPad: '加入成为WishPad',
      support: '支持',
      faq: '常见问题',
      contactUs: '联系我们',
      privacyPolicy: '隐私政策',
      legal: '法律',
      termsOfService: '服务条款',
      cookiePolicy: 'Cookie政策',
      allRightsReserved: '版权所有。',
    },
    daysLeft: '剩余{days}天',
    today: '今天',
  },
  sw: {
    name: 'Kiswahili',
    flag: '🇰🇪',
    hero: {
      badge: 'Jukwaa la Kulinganisha Matamanio kwa AI',
      title: 'Una tamaa? WishPal inatimiza —',
      subtitle: 'inayoendeshwa na AI na 100% bure. Jaribu sasa',
      formula: 'Tamaa Yako + WishPal = Suluhisho Lako',
      cta: { free: 'Ni Bure, anza sasa', makeWish: 'Tengeneza Tamaa', explore: 'Chunguza Matamanio' },
      search: { placeholder: 'Tafuta matamanio... mf: "kusafisha nyumba", "kazi ya programu"', button: 'Tafuta' },
    },
    ticker: {
      mostSuccessful: 'Matamanio yaliyofanikiwa wiki hii:',
      jobsFound: 'Kazi zilizopatikana',
      productsBought: 'Bidhaa zilizonunuliwa',
      usersAdvised: 'Watumiaji waliopewa ushauri bure',
      trending: 'Yanayovuma:',
      wishesFulfilled: 'Matamanio yaliyotimizwa',
      activeWishes: 'Matamanio hai',
      beingPosted: 'Yanachapishwa sasa',
    },
    stats: {
      liveNow: 'Moja kwa Moja',
      wishesLive: 'Matamanio Moja kwa Moja',
      closedThisWeek: 'Yamefunga Wiki Hii',
      beingPostedNow: 'Yanachapishwa Sasa',
      updatingRealTime: 'Inasasishwa kwa wakati halisi',
    },
    banner: {
      wishesLiveNow: 'Matamanio Moja kwa Moja',
      closedThisWeek: 'Yamefunga Wiki Hii',
      jobsFound: 'Kazi Zilizopatikana',
      productsBought: 'Bidhaa Zilizonunuliwa',
    },
    noticeBoard: {
      title: 'Ubao wa Matangazo',
      viewAll: 'Ona yote',
      empty: 'Hakuna matamanio yaliyochapishwa. Kuwa wa kwanza!',
    },
    map: {
      title: 'Ramani ya WishPad',
      allCountries: 'Nchi Zote',
      matches: 'zinazolingana',
      viewPage: 'Tazama Ukurasa',
    },
    closingSoon: {
      title: 'Kufunga Karibuni',
      empty: 'Hakuna matamanio yanayofunga karibuni',
      lastDay: 'Siku ya Mwisho!',
    },
    topWishpads: {
      title: 'Chunguza WishPads Bora',
      subtitle: 'Gundua biashara na watoa huduma walio tayari kutimiza matamanio yako duniani kote',
      empty: 'Hakuna WishPads zilizosajiliwa. Kuwa wa kwanza!',
      register: 'Jisajili kama WishPad',
      matches: 'zinazolingana',
    },
    testimonials: {
      title: 'Hadithi za Mafanikio',
      subtitle: 'Watu halisi, matokeo halisi — yanayoendeshwa na WishPal',
      verified: 'Imethibitishwa',
    },
    features: {
      title: 'Kwa Nini Sote Tunahitaji WishPal',
      subtitle: 'Jukwaa linalounganisha matamanio na fursa',
      revenue: { title: 'Kizalishaji Mapato', desc: 'Geuza matamanio kuwa mapato. Biashara huunganishwa na wateja wanaotafuta huduma zao.' },
      costSaving: { title: 'Chombo cha Kuokoa', desc: 'Okoa pesa kwa kupata kile unachohitaji. Hakuna matangazo ghali au ada za wakala.' },
      informative: { title: 'Taarifa', desc: 'Ufahamu wa AI kwa kila tamaa. Ulinganishaji mahiri na mapendekezo yanayotokana na data.' },
      problemSolving: { title: 'Utatuzi wa Matatizo', desc: 'Una tatizo? Weka tamaa na acha AI yetu ikupatie suluhisho kamili.' },
    },
    tagline: {
      title: 'WishPal: Chombo cha pekee kwa mahitaji yako yote wakati wote',
      subtitle: 'Matamanio yako, yanayolinganishwa na AI. Kila wakati, kila mahitaji.',
      cta: 'Ni Bure, anza sasa',
    },
    footer: {
      description: 'Matamanio yako, yanayolinganishwa na AI. Tunakuunganisha na watu sahihi kutimiza matamanio yako.',
      platform: 'Jukwaa',
      browseWishes: 'Vinjari Matamanio',
      joinWishMate: 'Jiunge kama WishMate',
      joinWishPad: 'Jiunge kama WishPad',
      support: 'Msaada',
      faq: 'Maswali',
      contactUs: 'Wasiliana Nasi',
      privacyPolicy: 'Sera ya Faragha',
      legal: 'Kisheria',
      termsOfService: 'Masharti ya Huduma',
      cookiePolicy: 'Sera ya Vidakuzi',
      allRightsReserved: 'Haki zote zimehifadhiwa.',
    },
    daysLeft: 'siku {days} zimebaki',
    today: 'Leo',
  },
  ar: {
    name: 'العربية',
    flag: '🇸🇦',
    rtl: true,
    hero: {
      badge: 'منصة مطابقة الرغبات بالذكاء الاصطناعي',
      title: 'لديك أمنية؟ WishPal يحققها —',
      subtitle: 'مدعوم بالذكاء الاصطناعي ومجاني 100%. جربه الآن',
      formula: 'أمنيتك + WishPal = حلك',
      cta: { free: 'إنه مجاني، ابدأ الآن', makeWish: 'تقديم أمنية', explore: 'استكشاف الأمنيات' },
      search: { placeholder: 'بحث عن أمنيات... مثال: "تنظيف منزل"، "وظيفة مطور ويب"', button: 'بحث' },
    },
    ticker: {
      mostSuccessful: 'الأمنيات الأكثر نجاحاً هذا الأسبوع:',
      jobsFound: 'وظائف وجدت',
      productsBought: 'منتجات اشتراها',
      usersAdvised: 'مستخدمين نُصحوا مجاناً',
      trending: 'الأكثر رواجاً:',
      wishesFulfilled: 'أمنيات تحققت',
      activeWishes: 'أمنيات نشطة',
      beingPosted: 'تُنشر الآن',
    },
    stats: {
      liveNow: 'مباشر',
      wishesLive: 'أمنيات مباشرة',
      closedThisWeek: 'أغلقت هذا الأسبوع',
      beingPostedNow: 'تُنشر الآن',
      updatingRealTime: 'التحديث في الوقت الفعلي',
    },
    banner: {
      wishesLiveNow: 'أمنيات مباشرة',
      closedThisWeek: 'أغلقت هذا الأسبوع',
      jobsFound: 'وظائف وجدت',
      productsBought: 'منتجات اشتراها',
    },
    noticeBoard: {
      title: 'لوحة الإعلانات',
      viewAll: 'عرض الكل',
      empty: 'لا توجد أمنيات منشورة بعد. كن الأول!',
    },
    map: {
      title: 'خريطة WishPad',
      allCountries: 'جميع البلدان',
      matches: 'مطابقة',
      viewPage: 'عرض الصفحة',
    },
    closingSoon: {
      title: 'تغلق قريباً',
      empty: 'لا توجد أمنيات تغلق قريباً',
      lastDay: 'اليوم الأخير!',
    },
    topWishpads: {
      title: 'استكشاف أفضل WishPads',
      subtitle: 'اكتشف الشركات ومقدمي الخدمات المستعدين لتحقيق أمنياتك في جميع أنحاء العالم',
      empty: 'لا توجد WishPads مسجلة بعد. كن الأول!',
      register: 'التسجيل كـ WishPad',
      matches: 'مطابقة',
    },
    testimonials: {
      title: 'قصص النجاح',
      subtitle: 'أناس حقيقيون، نتائج حقيقية — مدعومة من WishPal',
      verified: 'موثّق',
    },
    features: {
      title: 'لماذا نحتاج جميعاً إلى WishPal',
      subtitle: 'المنصة التي تربط الأمنيات بالفرص',
      revenue: { title: 'مدرة للدخل', desc: 'حول الأمنيات إلى دخل. تتواصل الشركات مع العملاء الذين يبحثون بنشاط عن خدماتهم.' },
      costSaving: { title: 'أداة توفير', desc: 'وفر المال بالعثور على ما تحتاجه بالضبط من خلال المطابقة القائمة على الأمنيات. لا إعلانات باهظة.' },
      informative: { title: 'غني بالمعلومات', desc: 'رؤى مدعومة بالذكاء الاصطناعي لكل أمنية. مطابقة ذكية وتوصيات مبنية على البيانات.' },
      problemSolving: { title: 'حل المشكلات', desc: 'لديك مشكلة؟ انشر أمنية ودع الذكاء الاصطناعي لدينا يجد لك الحل الأمثل.' },
    },
    tagline: {
      title: 'WishPal: الأداة الوحيدة لجميع احتياجاتك في كل الأوقات',
      subtitle: 'أمنياتك، متطابقة بالذكاء الاصطناعي. كل مرة، كل حاجة.',
      cta: 'إنه مجاني، ابدأ الآن',
    },
    footer: {
      description: 'أمنياتك، متطابقة بالذكاء الاصطناعي. نوصلك بالأشخاص المناسبين لتحقيق أمنياتك.',
      platform: 'المنصة',
      browseWishes: 'تصفح الأمنيات',
      joinWishMate: 'انضم كـ WishMate',
      joinWishPad: 'انضم كـ WishPad',
      support: 'الدعم',
      faq: 'الأسئلة الشائعة',
      contactUs: 'اتصل بنا',
      privacyPolicy: 'سياسة الخصوصية',
      legal: 'قانوني',
      termsOfService: 'شروط الخدمة',
      cookiePolicy: 'سياسة ملفات تعريف الارتباط',
      allRightsReserved: 'جميع الحقوق محفوظة.',
    },
    daysLeft: '{days} أيام متبقية',
    today: 'اليوم',
  },
  pt: {
    name: 'Português',
    flag: '🇵🇹',
    hero: {
      badge: 'Plataforma de Correspondência de Desejos com IA',
      title: 'Tem um desejo? WishPal realiza —',
      subtitle: 'alimentado por IA e 100% gratuito. Experimente agora',
      formula: 'Seu Desejo + WishPal = Sua Solução',
      cta: { free: 'É grátis, comece agora', makeWish: 'Fazer um Desejo', explore: 'Explorar Desejos' },
      search: { placeholder: 'Pesquisar desejos... ex: "limpeza", "emprego programador"', button: 'Pesquisar' },
    },
    ticker: {
      mostSuccessful: 'Desejos mais bem-sucedidos esta semana:',
      jobsFound: 'Empregos encontrados',
      productsBought: 'Produtos comprados',
      usersAdvised: 'Utilizadores aconselhados grátis',
      trending: 'Tendências:',
      wishesFulfilled: 'Desejos realizados',
      activeWishes: 'Desejos ativos',
      beingPosted: 'A ser publicados agora',
    },
    stats: {
      liveNow: 'Ao Vivo',
      wishesLive: 'Desejos ao Vivo',
      closedThisWeek: 'Fechados Esta Semana',
      beingPostedNow: 'A Serem Publicados Agora',
      updatingRealTime: 'Atualizando em tempo real',
    },
    banner: {
      wishesLiveNow: 'Desejos ao Vivo',
      closedThisWeek: 'Fechados Esta Semana',
      jobsFound: 'Empregos Encontrados',
      productsBought: 'Produtos Comprados',
    },
    noticeBoard: {
      title: 'Quadro de Avisos',
      viewAll: 'Ver tudo',
      empty: 'Nenhum desejo publicado ainda. Seja o primeiro!',
    },
    map: {
      title: 'Mapa WishPad',
      allCountries: 'Todos os Países',
      matches: 'correspondências',
      viewPage: 'Ver Página',
    },
    closingSoon: {
      title: 'A Fechar em Breve',
      empty: 'Nenhum desejo a fechar em breve',
      lastDay: 'Último dia!',
    },
    topWishpads: {
      title: 'Explorar os Melhores WishPads',
      subtitle: 'Descubra empresas e prestadores de serviços prontos para realizar seus desejos em todo o mundo',
      empty: 'Nenhum WishPad registrado ainda. Seja o primeiro!',
      register: 'Registrar como WishPad',
      matches: 'correspondências',
    },
    testimonials: {
      title: 'Histórias de Sucesso',
      subtitle: 'Pessoas reais, resultados reais — alimentados por WishPal',
      verified: 'Verificado',
    },
    features: {
      title: 'Por Que Todos Precisamos do WishPal',
      subtitle: 'A plataforma que conecta desejos a oportunidades',
      revenue: { title: 'Gerador de Receita', desc: 'Transforme desejos em receita. Empresas conectam-se com clientes que procuram ativamente seus serviços.' },
      costSaving: { title: 'Ferramenta de Economia', desc: 'Economize encontrando exatamente o que precisa. Sem anúncios caros ou taxas de intermediários.' },
      informative: { title: 'Informativo', desc: 'Insights alimentados por IA para cada desejo. Correspondência inteligente e recomendações baseadas em dados.' },
      problemSolving: { title: 'Resolução de Problemas', desc: 'Tem um problema? Publique um desejo e deixe nossa IA encontrar a solução perfeita.' },
    },
    tagline: {
      title: 'WishPal: A única ferramenta para todas as suas necessidades em todos os momentos',
      subtitle: 'Seus desejos, combinados por IA. Toda vez, toda necessidade.',
      cta: 'É grátis, comece agora',
    },
    footer: {
      description: 'Seus desejos, combinados por IA. Conectamo-lo com as pessoas certas para realizar seus desejos.',
      platform: 'Plataforma',
      browseWishes: 'Explorar Desejos',
      joinWishMate: 'Juntar-se como WishMate',
      joinWishPad: 'Juntar-se como WishPad',
      support: 'Suporte',
      faq: 'FAQ',
      contactUs: 'Fale Connosco',
      privacyPolicy: 'Política de Privacidade',
      legal: 'Legal',
      termsOfService: 'Termos de Serviço',
      cookiePolicy: 'Política de Cookies',
      allRightsReserved: 'Todos os direitos reservados.',
    },
    daysLeft: '{days}d restantes',
    today: 'Hoje',
  },
  zu: {
    name: 'isiZulu',
    flag: '🇿🇦',
    navbar: { home: 'Ikhaya', search: 'Sesha', dashboard: 'Ideshibhodi' },
    hero: {
      badge: 'Inkundla Yokufanisa Izifiso nge-AI',
      title: 'Unesifiso? WishPal iyayifeza —',
      subtitle: 'iqhutshwa yi-AI futhi mahhala 100%. Zama manje',
      formula: 'Isifiso Sakho + WishPal = Isixazululo Sakho',
      cta: { free: 'Kumahhala, qala manje', makeWish: 'Yenza Isifiso', explore: 'Hlola Izifiso' },
      search: { placeholder: 'Sesha izifiso... isb: "ukuhlanza indlu", "umsebenzi wokuthuthuka"', button: 'Sesha' },
    },
    ticker: {
      mostSuccessful: 'Izifiso eziphumelele kakhulu kuleli sonto:',
      jobsFound: 'Imisebenzi etholakele',
      productsBought: 'Imikhiqizo ethengiwe',
      usersAdvised: 'Abasebenzisi belulekwe mahhala',
      trending: 'Eziyathandwa:',
      wishesFulfilled: 'Izifiso ezigcwalisekile',
      activeWishes: 'Izifiso ezisebenzayo',
      beingPosted: 'Ezithunyelwa manje',
    },
    stats: {
      liveNow: 'Buqophe',
      wishesLive: 'Izifiso Eziphilayo',
      closedThisWeek: 'Zivalwe Kuleli Sonto',
      beingPostedNow: 'Ziyathunyelwa Manje',
      updatingRealTime: 'Kubuyekezwa ngesikhathi sangempela',
    },
    banner: {
      wishesLiveNow: 'Izifiso Eziphilayo',
      closedThisWeek: 'Zivalwe Kuleli Sonto',
      jobsFound: 'Imisebenzi Etholakele',
      productsBought: 'Imikhiqizo Ethengiwe',
    },
    noticeBoard: {
      title: 'Ibhodi Lezaziso',
      viewAll: 'Buka konke',
      empty: 'Azikho izifiso ezithunyelwe. Yiba ngowokuqala!',
    },
    map: {
      title: 'Ibalazwe Le-WishPad',
      allCountries: 'Wonke Amazwe',
      matches: 'okufaniswayo',
      viewPage: 'Buka Ikhasi',
    },
    closingSoon: {
      title: 'Kuvala Ngokushesha',
      empty: 'Azikho izifiso ezivalwa maduze',
      lastDay: 'Usuku Lokugcina!',
    },
    topWishpads: {
      title: 'Hlola Ama-WishPad Aphambili',
      subtitle: 'Zitholele amabhizinisi nabasebenzisi abakulungele ukufeza izifiso zakho emhlabeni wonke',
      empty: 'Awekho ama-WishPad abhalisiwe. Yiba ngowokuqala!',
      register: 'Bhalisa njenge-WishPad',
      matches: 'okufaniswayo',
    },
    testimonials: {
      title: 'Izindaba Zempumelelo',
      subtitle: 'Abantu bangempela, imiphumela yangempela — iqhutshwa yi-WishPal',
      verified: 'Kuqinisekisiwe',
    },
    features: {
      title: 'Kungani Sonke Siyidinga i-WishPal',
      subtitle: 'Inkundla ehlanganisa izifiso namathuba',
      revenue: { title: 'Umkhiqizi Wemali', desc: 'Guqula izifiso zibe ngumholo. Amabhizinisi athola amakhasimende afuna izinsiza zawo.' },
      costSaving: { title: 'Ithuluzi Lokonga', desc: 'Yonga imali ngokuthola lokho okudingayo. Azikho izikhangiso ezibizayo noma izindleko zomlamuli.' },
      informative: { title: 'Imininingwane', desc: 'Ukuqondisa okuqhutshwa yi-AI kusifiso ngasinye. Ukufanisa okuhlakaniphile nezincomo eziqhutshwa idatha.' },
      problemSolving: { title: 'Ukuxazulula Izinkinga', desc: 'Unenkinga? Thumela isifiso uvumele i-AI yethu ikutholele isixazululo esiphelele.' },
    },
    tagline: {
      title: 'I-WishPal: Ithuluzi elilodwa kuzo zonke izidingo zakho ngazo zonke izikhathi',
      subtitle: 'Izifiso zakho, zifaniswe yi-AI. Njalo, sonke isidingo.',
      cta: 'Kumahhala, qala manje',
    },
    footer: {
      description: 'Izifiso zakho, zifaniswe yi-AI. Sikuxhuma nabantu abafanele ukugcwalisa izifiso zakho.',
      platform: 'Inkundla',
      browseWishes: 'Hlola Izifiso',
      joinWishMate: 'Hlanganyela njenge-WishMate',
      joinWishPad: 'Hlanganyela njenge-WishPad',
      support: 'Ukusekela',
      faq: 'Imibuzo Evame',
      contactUs: 'Xhumana Nathi',
      privacyPolicy: 'Inqubomgomo Yobumfihlo',
      legal: 'Okusemthethweni',
      termsOfService: 'Imigomo Yesevisi',
      cookiePolicy: 'Inqubomgomo Yama-Cookie',
      allRightsReserved: 'Wonke amalungelo agodliwe.',
    },
    daysLeft: 'kusale {days} izinsuku',
    today: 'Namuhla',
  },
  de: {
    name: 'Deutsch',
    flag: '🇩🇪',
    navbar: { home: 'Startseite', search: 'Suche', dashboard: 'Dashboard' },
    hero: {
      badge: 'KI-gestützte Wunschvermittlungsplattform',
      title: 'Hast du einen Wunsch? WishPal macht es möglich —',
      subtitle: 'unterstützt von KI und 100% kostenlos. Probier es jetzt aus',
      formula: 'Dein Wunsch + WishPal = Deine Lösung',
      cta: { free: 'Es ist kostenlos, starte jetzt', makeWish: 'Einen Wunsch äußern', explore: 'Wünsche erkunden' },
      search: { placeholder: 'Wünsche suchen... z.B. "Hausreinigung", "Webentwickler-Job"', button: 'Suchen' },
    },
    ticker: {
      mostSuccessful: 'Erfolgreichste Wünsche diese Woche:',
      jobsFound: 'Jobs gefunden',
      productsBought: 'Produkte gekauft',
      usersAdvised: 'Kostenlos beraten',
      trending: 'Im Trend:',
      wishesFulfilled: 'Erfüllte Wünsche',
      activeWishes: 'Aktive Wünsche',
      beingPosted: 'Werden jetzt gepostet',
    },
    stats: {
      liveNow: 'Live',
      wishesLive: 'Live-Wünsche',
      closedThisWeek: 'Diese Woche geschlossen',
      beingPostedNow: 'Werden jetzt gepostet',
      updatingRealTime: 'Echtzeit-Updates',
    },
    banner: {
      wishesLiveNow: 'Live-Wünsche',
      closedThisWeek: 'Diese Woche geschlossen',
      jobsFound: 'Gefundene Jobs',
      productsBought: 'Gekaufte Produkte',
    },
    noticeBoard: {
      title: 'Schwarzes Brett',
      viewAll: 'Alle anzeigen',
      empty: 'Noch keine Wünsche gepostet. Sei der Erste!',
    },
    map: {
      title: 'WishPad-Karte',
      allCountries: 'Alle Länder',
      matches: 'Übereinstimmungen',
      viewPage: 'Seite anzeigen',
    },
    closingSoon: {
      title: 'Schließen bald',
      empty: 'Keine Wünsche schließen bald',
      lastDay: 'Letzter Tag!',
    },
    topWishpads: {
      title: 'Top WishPads entdecken',
      subtitle: 'Entdecke Unternehmen und Dienstleister, die bereit sind, deine Wünsche weltweit zu erfüllen',
      empty: 'Noch keine WishPads registriert. Sei der Erste!',
      register: 'Als WishPad registrieren',
      matches: 'Übereinstimmungen',
    },
    testimonials: {
      title: 'Erfolgsgeschichten',
      subtitle: 'Echte Menschen, echte Ergebnisse — unterstützt von WishPal',
      verified: 'Verifiziert',
    },
    features: {
      title: 'Warum wir alle WishPal brauchen',
      subtitle: 'Die Plattform, die Wünsche mit Chancen verbindet',
      revenue: { title: 'Einnahmequelle', desc: 'Verwandle Wünsche in Einnahmen. Unternehmen werden mit Kunden zusammengebracht, die aktiv nach ihren Dienstleistungen suchen.' },
      costSaving: { title: 'Kostensparer', desc: 'Spare Geld, indem du genau das findest, was du brauchst. Keine teuren Anzeigen oder Vermittlungsgebühren.' },
      informative: { title: 'Informativ', desc: 'KI-gestützte Einblicke für jeden Wunsch. Intelligente Vermittlung und datenbasierte Empfehlungen.' },
      problemSolving: { title: 'Problemlösung', desc: 'Hast du ein Problem? Veröffentliche einen Wunsch und lass unsere KI die perfekte Lösung finden.' },
    },
    tagline: {
      title: 'WishPal: Das einzige Werkzeug für alle deine Bedürfnisse zu jeder Zeit',
      subtitle: 'Deine Wünsche, gematcht von KI. Jedes Mal, jedes Bedürfnis.',
      cta: 'Es ist kostenlos, starte jetzt',
    },
    footer: {
      description: 'Deine Wünsche, gematcht von KI. Wir verbinden dich mit den richtigen Leuten, um deine Wünsche zu erfüllen.',
      platform: 'Plattform',
      browseWishes: 'Wünsche durchstöbern',
      joinWishMate: 'Als WishMate beitreten',
      joinWishPad: 'Als WishPad beitreten',
      support: 'Support',
      faq: 'FAQ',
      contactUs: 'Kontaktiere uns',
      privacyPolicy: 'Datenschutzerklärung',
      legal: 'Rechtliches',
      termsOfService: 'Nutzungsbedingungen',
      cookiePolicy: 'Cookie-Richtlinie',
      allRightsReserved: 'Alle Rechte vorbehalten.',
    },
    daysLeft: 'noch {days} Tage',
    today: 'Heute',
  },
  st: {
    name: 'Sesotho',
    flag: '🇱🇸',
    navbar: { home: 'Lapeng', search: 'Batla', dashboard: 'Dashboard' },
    hero: {
      badge: 'Sethala sa ho Bapatsa Litakatso ka AI',
      title: 'O na le takatso? WishPal ea e phetha —',
      subtitle: 'e tsamaisoa ke AI mme e le mahala 100%. E leka hona joale',
      formula: 'Takatso ea Hao + WishPal = Tharollo ea Hao',
      cta: { free: 'E mahala, qala hona joale', makeWish: 'Etsa Takatso', explore: 'Hlola Litakatso' },
      search: { placeholder: 'Batla litakatso... mohl: "ho hloekisa ntlo", "mosebetsi oa ntlafatso"', button: 'Batla' },
    },
    ticker: {
      mostSuccessful: 'Litakatso tse atlehileng ka ho fetesisa bekeng ena:',
      jobsFound: 'Mesebetsi e fumanoeng',
      productsBought: 'Lihlahisoa tse rekiloeng',
      usersAdvised: 'Basebelisi ba elelitsoe mahala',
      trending: 'Tse tumileng:',
      wishesFulfilled: 'Litakatso tse phethahetseng',
      activeWishes: 'Litakatso tse sebetsang',
      beingPosted: 'Tse ntseng li romelloa hona joale',
    },
    stats: {
      liveNow: 'Phela Hona Joale',
      wishesLive: 'Litakatso tse Phelang',
      closedThisWeek: 'Li Koetsoe Bekeng Ena',
      beingPostedNow: 'Li Romelloa Hona Joale',
      updatingRealTime: 'E ntlafatsoa ka nako ea sebele',
    },
    banner: {
      wishesLiveNow: 'Litakatso tse Phelang',
      closedThisWeek: 'Li Koetsoe Bekeng Ena',
      jobsFound: 'Mesebetsi e Fumanoeng',
      productsBought: 'Lihlahisoa tse Rekiloeng',
    },
    noticeBoard: {
      title: 'Letlapa la Litsebiso',
      viewAll: 'Bona kaofela',
      empty: 'Ha ho litakatso tse rometsoeng. Eba oa pele!',
    },
    map: {
      title: '\'Mapa oa WishPad',
      allCountries: 'Lintho Tsohle',
      matches: 'tse lumellanang',
      viewPage: 'Bona Leqephe',
    },
    closingSoon: {
      title: 'E Koahela Haufinyane',
      empty: 'Ha ho litakatso tse koaloang haufinyane',
      lastDay: 'Letsatsi la ho Qetela!',
    },
    topWishpads: {
      title: 'Hlola Li-WishPad tse Holimo',
      subtitle: 'Fumana likhoebo le bafani ba litšebeletso ba lokiselitsoeng ho phethahatsa litakatso tsa hau lefatšeng ka bophara',
      empty: 'Ha ho li-WishPad tse ngolisitsoeng. Eba oa pele!',
      register: 'Ngolisa joalo ka WishPad',
      matches: 'tse lumellanang',
    },
    testimonials: {
      title: 'Lipale tsa Katleho',
      subtitle: 'Batho ba sebele, liphetho tsa sebele — li tsamaisoa ke WishPal',
      verified: 'E netefalitsoe',
    },
    features: {
      title: 'Hobaneng Kaofela Re Hloka WishPal',
      subtitle: 'Sethala se hokahanyang litakatso le menyetla',
      revenue: { title: 'Moetsi oa Lekeno', desc: 'Fetola litakatso hore e be lekено. Likhoebo li hokahanngoa le bareki ba batlang litšebeletso tsa bona ka mafolofolo.' },
      costSaving: { title: 'Sesebedisoa sa ho Boloka', desc: 'Boloka tjhelete ka ho fumana seo o se hlokang. Ha ho lipapatso tse turang kapa litefiso tsa bonkgetheng.' },
      informative: { title: 'Tlhahisoleseling', desc: 'Temoho e tsamaisoang ke AI bakeng sa takatso e ngoe le e ngoe. Ho bapatsa ho hlalefileng le litlhahiso tse thehiloeng ho data.' },
      problemSolving: { title: 'Ho Rarolla Mathata', desc: 'O na le bothata? Romella takatso mme o lumelle AI ea rona ho u fumanele tharollo e phethahetseng.' },
    },
    tagline: {
      title: 'WishPal: Sethala se le seng bakeng sa litlhoko tsohle tsa hau ka linako tsohle',
      subtitle: 'Litakatso tsa hau, li bapisoa ke AI. Nako e ngoe le e ngoe, tlhoko e ngoe le e ngoe.',
      cta: 'E mahala, qala hona joale',
    },
    footer: {
      description: 'Litakatso tsa hau, li bapisoa ke AI. Re u hokahanya le batho ba nepahetseng ho phethahatsa litakatso tsa hau.',
      platform: 'Sethala',
      browseWishes: 'Batla Litakatso',
      joinWishMate: 'Ikopanya joalo ka WishMate',
      joinWishPad: 'Ikopanya joalo ka WishPad',
      support: 'Tshehetso',
      faq: 'Lipotso',
      contactUs: 'Iteanye le Rona',
      privacyPolicy: 'Leano la Lekunutu',
      legal: 'Semolao',
      termsOfService: 'Meliya ea Tšebeletso',
      cookiePolicy: 'Leano la Cookie',
      allRightsReserved: 'Litokelo tsohle li sirelelitsoe.',
    },
    daysLeft: 'ho setse {days} matsatsi',
    today: 'Kajeno',
  },
  tn: {
    name: 'Setswana',
    flag: '🇧🇼',
    navbar: { home: 'Gae', search: 'Batla', dashboard: 'Dashboto' },
    hero: {
      badge: 'Sethala sa go Bapatsa Dikeletso ka AI',
      title: 'O na le keletso? WishPal e a e diragatsa —',
      subtitle: 'e tsamaisiwa ke AI mme e le mahala 100%. E leka jaanong',
      formula: 'Keletso ya Gago + WishPal = Tharollo ya Gago',
      cta: { free: 'Ke mahala, simolola jaanong', makeWish: 'Dira Keletso', explore: 'Batla Dikeletso' },
      search: { placeholder: 'Batla dikeletso... sekai: "go phepafatsa ntlo", "tiro ya web"', button: 'Batla' },
    },
    ticker: {
      mostSuccessful: 'Dikeletso tse di atlegileng thata bekeng e:',
      jobsFound: 'Ditiro tse di fitlhelweng',
      productsBought: 'Dihlahiswa tse di rekilweng',
      usersAdvised: 'Basebelisi ba gakololwa mahala',
      trending: 'Tse di tumileng:',
      wishesFulfilled: 'Dikeletso tse di diragaditsweng',
      activeWishes: 'Dikeletso tse di dirang',
      beingPosted: 'Di a romelwa jaanong',
    },
    stats: {
      liveNow: 'Tshela Jaanong',
      wishesLive: 'Dikeletso tse di Tshelang',
      closedThisWeek: 'Di Tswetswe Bekeng E',
      beingPostedNow: 'Di Romelwa Jaanong',
      updatingRealTime: 'Di ntlafadiwa ka nako ya nnete',
    },
    banner: {
      wishesLiveNow: 'Dikeletso tse di Tshelang',
      closedThisWeek: 'Di Tswetswe Bekeng E',
      jobsFound: 'Ditiro tse di Fitlhelweng',
      productsBought: 'Dihlahiswa tse di Rekilweng',
    },
    noticeBoard: {
      title: 'Letlapa la Dikitsiso',
      viewAll: 'Bona botlhe',
      empty: 'Ga go dikeletso tse di rometsweng. Nna wa ntlha!',
    },
    map: {
      title: 'Mapa wa WishPad',
      allCountries: 'Dinaga Tsotlhe',
      matches: 'tse di tshwanang',
      viewPage: 'Bona Tsebe',
    },
    closingSoon: {
      title: 'E Tswala Kapelenyana',
      empty: 'Ga go dikeletso tse di tswalwang kapelenyana',
      lastDay: 'Letsatsi la Bofelo!',
    },
    topWishpads: {
      title: 'Batla Di-WishPad tsa Godimo',
      subtitle: 'Fumana dikgwebo le bafani ba ditirelo ba ba ikemiseditseng go diragatsa dikeletso tsa gago lefatshe ka bophara',
      empty: 'Ga go di-WishPad tse di kwadisitsweng. Nna wa ntlha!',
      register: 'Ikwalisa jaaka WishPad',
      matches: 'tse di tshwanang',
    },
    testimonials: {
      title: 'Dikanegelo tsa Katlego',
      subtitle: 'Batho ba nnete, diphetho tsa nnete — di tsamaiswa ke WishPal',
      verified: 'E netefaditswe',
    },
    features: {
      title: 'Goreng Rotlhe Re Tlhoka WishPal',
      subtitle: 'Sethala se se gokaganyang dikeletso le ditšhono',
      revenue: { title: 'Modiri wa Maduo', desc: 'Fetola dikeletso gore e me maduo. Dikgwebo di gokaganywa le bareki ba ba batlang ditirelo tsa bona ka tlhoafalo.' },
      costSaving: { title: 'Sediriswa sa go Boloka', desc: 'Boloka madi ka go bona se o se tlhokang. Ga go dipapatso tse di turang kgotsa ditefelo tsa tsamaiso.' },
      informative: { title: 'Tlhahisoleseding', desc: 'Temogo e tsamaiswang ke AI mo keletsong nngwe le nngwe. Go bapatsa go botlhale le ditshitshinyo tse di tsamaiswang ke data.' },
      problemSolving: { title: 'Go Rarabolola Mathata', desc: 'O na le bothata? Romela keletso mme o tlogele AI ya rona go go fitlhela tharollo e e tshwanetseng.' },
    },
    tagline: {
      title: 'WishPal: Sediriswa se le seng sa ditlhoko tsotlhe tsa gago ka dinako tsotlhe',
      subtitle: 'Dikeletso tsa gago, di bapaditswe ke AI. Nako nngwe le nngwe, tlhoko nngwe le nngwe.',
      cta: 'Ke mahala, simolola jaanong',
    },
    footer: {
      description: 'Dikeletso tsa gago, di bapaditswe ke AI. Re go gokaganya le batho ba ba tshwanetseng go diragatsa dikeletso tsa gago.',
      platform: 'Sethala',
      browseWishes: 'Batla Dikeletso',
      joinWishMate: 'Ikopanya jaaka WishMate',
      joinWishPad: 'Ikopanya jaaka WishPad',
      support: 'Kemonokeng',
      faq: 'Dipotso',
      contactUs: 'Ikgolaganye le Rona',
      privacyPolicy: 'Polaisi ya Sehiding',
      legal: 'Semolao',
      termsOfService: 'Melawana ya Tirelo',
      cookiePolicy: 'Polaisi ya Cookie',
      allRightsReserved: 'Ditokelo tsotlhe di sireleditswe.',
    },
    daysLeft: 'go setse {days} malatsi',
    today: 'Gompieno',
  },
  hi: {
    name: 'हिन्दी',
    flag: '🇮🇳',
    navbar: { home: 'होम', search: 'खोज', dashboard: 'डैशबोर्ड' },
    hero: {
      badge: 'AI-संचालित इच्छा मिलान प्लेटफ़ॉर्म',
      title: 'कोई इच्छा? WishPal इसे पूरा करता है —',
      subtitle: 'AI द्वारा संचालित और 100% मुफ्त। अभी आज़माएं',
      formula: 'आपकी इच्छा + WishPal = आपका समाधान',
      cta: { free: 'यह मुफ्त है, अभी शुरू करें', makeWish: 'इच्छा करें', explore: 'इच्छाएं देखें' },
      search: { placeholder: 'इच्छाएं खोजें... जैसे: "घर की सफाई", "वेब डेवलपर नौकरी"', button: 'खोज' },
    },
    ticker: {
      mostSuccessful: 'इस सप्ताह की सबसे सफल इच्छाएं:',
      jobsFound: 'नौकरियां मिलीं',
      productsBought: 'उत्पाद खरीदे गए',
      usersAdvised: 'उपयोगकर्ताओं को मुफ्त सलाह',
      trending: 'ट्रेंडिंग:',
      wishesFulfilled: 'इच्छाएं पूरी हुईं',
      activeWishes: 'सक्रिय इच्छाएं',
      beingPosted: 'अभी पोस्ट की जा रही हैं',
    },
    stats: {
      liveNow: 'लाइव',
      wishesLive: 'लाइव इच्छाएं',
      closedThisWeek: 'इस सप्ताह बंद हुईं',
      beingPostedNow: 'अभी पोस्ट की जा रही हैं',
      updatingRealTime: 'रीयल-टाइम में अपडेट',
    },
    banner: {
      wishesLiveNow: 'लाइव इच्छाएं',
      closedThisWeek: 'इस सप्ताह बंद हुईं',
      jobsFound: 'नौकरियां मिलीं',
      productsBought: 'उत्पाद खरीदे गए',
    },
    noticeBoard: {
      title: 'सूचना पटल',
      viewAll: 'सभी देखें',
      empty: 'अभी तक कोई इच्छा पोस्ट नहीं हुई। पहले बनें!',
    },
    map: {
      title: 'WishPad मानचित्र',
      allCountries: 'सभी देश',
      matches: 'मिलान',
      viewPage: 'पेज देखें',
    },
    closingSoon: {
      title: 'जल्द बंद हो रहा है',
      empty: 'कोई इच्छा जल्द बंद नहीं हो रही',
      lastDay: 'आखिरी दिन!',
    },
    topWishpads: {
      title: 'शीर्ष WishPads देखें',
      subtitle: 'उन व्यवसायों और सेवा प्रदाताओं की खोज करें जो दुनिया भर में आपकी इच्छाओं को पूरा करने के लिए तैयार हैं',
      empty: 'अभी तक कोई WishPad पंजीकृत नहीं। पहले बनें!',
      register: 'WishPad के रूप में पंजीकरण करें',
      matches: 'मिलान',
    },
    testimonials: {
      title: 'सफलता की कहानियां',
      subtitle: 'वास्तविक लोग, वास्तविक परिणाम — WishPal द्वारा संचालित',
      verified: 'सत्यापित',
    },
    features: {
      title: 'हम सभी को WishPal की आवश्यकता क्यों है',
      subtitle: 'वह प्लेटफ़ॉर्म जो इच्छाओं को अवसरों से जोड़ता है',
      revenue: { title: 'आय उत्पादक', desc: 'इच्छाओं को आय में बदलें। व्यवसाय उन ग्राहकों से जुड़ते हैं जो सक्रिय रूप से उनकी सेवाओं की तलाश में हैं।' },
      costSaving: { title: 'लागत बचत उपकरण', desc: 'इच्छा-आधारित मिलान के माध्यम से वही पाएं जो आपको चाहिए। कोई महंगे विज्ञापन या बिचौलिया शुल्क नहीं।' },
      informative: { title: 'जानकारीपूर्ण', desc: 'हर इच्छा पर AI-संचालित अंतर्दृष्टि। स्मार्ट मिलान, बाजार खुफिया और डेटा-संचालित अनुशंसाएं।' },
      problemSolving: { title: 'समस्या समाधान', desc: 'कोई समस्या है? एक इच्छा पोस्ट करें और हमारे AI को आपके लिए सही समाधान खोजने दें।' },
    },
    tagline: {
      title: 'WishPal: सभी समय आपकी सभी ज़रूरतों के लिए एकमात्र उपकरण',
      subtitle: 'आपकी इच्छाएं, AI द्वारा मिलान। हर बार, हर ज़रूरत।',
      cta: 'यह मुफ्त है, अभी शुरू करें',
    },
    footer: {
      description: 'आपकी इच्छाएं, AI द्वारा मिलान। हम आपको आपकी इच्छाओं को पूरा करने के लिए सही लोगों से जोड़ते हैं।',
      platform: 'प्लेटफ़ॉर्म',
      browseWishes: 'इच्छाएं ब्राउज़ करें',
      joinWishMate: 'WishMate के रूप में शामिल हों',
      joinWishPad: 'WishPad के रूप में शामिल हों',
      support: 'सहायता',
      faq: 'सामान्य प्रश्न',
      contactUs: 'संपर्क करें',
      privacyPolicy: 'गोपनीयता नीति',
      legal: 'कानूनी',
      termsOfService: 'सेवा की शर्तें',
      cookiePolicy: 'कुकी नीति',
      allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    },
    daysLeft: '{days} दिन बाकी',
    today: 'आज',
  },
  bn: {
    name: 'বাংলা',
    flag: '🇧🇩',
    navbar: { home: 'হোম', search: 'অনুসন্ধান', dashboard: 'ড্যাশবোর্ড' },
    hero: {
      badge: 'AI-চালিত ইচ্ছা মেলানোর প্ল্যাটফর্ম',
      title: 'একটি ইচ্ছা আছে? WishPal তা পূরণ করে —',
      subtitle: 'AI দ্বারা চালিত এবং 100% বিনামূল্যে। এখনই চেষ্টা করুন',
      formula: 'আপনার ইচ্ছা + WishPal = আপনার সমাধান',
      cta: { free: 'এটি বিনামূল্যে, এখনই শুরু করুন', makeWish: 'একটি ইচ্ছা করুন', explore: 'ইচ্ছাগুলি দেখুন' },
      search: { placeholder: 'ইচ্ছা অনুসন্ধান করুন... যেমন: "বাড়ি পরিষ্কার", "ওয়েব ডেভেলপার চাকরি"', button: 'অনুসন্ধান' },
    },
    ticker: {
      mostSuccessful: 'এই সপ্তাহের সবচেয়ে সফল ইচ্ছা:',
      jobsFound: 'চাকরি পাওয়া গেছে',
      productsBought: 'পণ্য কেনা হয়েছে',
      usersAdvised: 'ব্যবহারকারীদের বিনামূল্যে পরামর্শ',
      trending: 'ট্রেন্ডিং:',
      wishesFulfilled: 'ইচ্ছা পূরণ হয়েছে',
      activeWishes: 'সক্রিয় ইচ্ছা',
      beingPosted: 'এখন পোস্ট করা হচ্ছে',
    },
    stats: {
      liveNow: 'লাইভ',
      wishesLive: 'লাইভ ইচ্ছা',
      closedThisWeek: 'এই সপ্তাহে বন্ধ হয়েছে',
      beingPostedNow: 'এখন পোস্ট করা হচ্ছে',
      updatingRealTime: 'রিয়েল-টাইমে আপডেট',
    },
    banner: {
      wishesLiveNow: 'লাইভ ইচ্ছা',
      closedThisWeek: 'এই সপ্তাহে বন্ধ হয়েছে',
      jobsFound: 'চাকরি পাওয়া গেছে',
      productsBought: 'পণ্য কেনা হয়েছে',
    },
    noticeBoard: {
      title: 'নোটিশ বোর্ড',
      viewAll: 'সব দেখুন',
      empty: 'এখনও কোন ইচ্ছা পোস্ট করা হয়নি। প্রথম হোন!',
    },
    map: {
      title: 'WishPad মানচিত্র',
      allCountries: 'সব দেশ',
      matches: 'মিলেছে',
      viewPage: 'পৃষ্ঠা দেখুন',
    },
    closingSoon: {
      title: 'শীঘ্রই বন্ধ হচ্ছে',
      empty: 'শীঘ্রই বন্ধ হওয়ার মতো কোন ইচ্ছা নেই',
      lastDay: 'শেষ দিন!',
    },
    topWishpads: {
      title: 'শীর্ষ WishPads অন্বেষণ করুন',
      subtitle: 'ব্যবসা এবং পরিষেবা প্রদানকারীদের আবিষ্কার করুন যারা বিশ্বব্যাপী আপনার ইচ্ছা পূরণ করতে প্রস্তুত',
      empty: 'এখনও কোন WishPad নিবন্ধিত হয়নি। প্রথম হোন!',
      register: 'WishPad হিসেবে নিবন্ধন করুন',
      matches: 'মিলেছে',
    },
    testimonials: {
      title: 'সাফল্যের গল্প',
      subtitle: 'বাস্তব মানুষ, বাস্তব ফলাফল — WishPal দ্বারা চালিত',
      verified: 'যাচাই করা হয়েছে',
    },
    features: {
      title: 'কেন আমাদের সবার WishPal প্রয়োজন',
      subtitle: 'প্ল্যাটফর্ম যা ইচ্ছাকে সুযোগের সাথে সংযুক্ত করে',
      revenue: { title: 'আয় উৎপাদক', desc: 'ইচ্ছাকে আয়ে পরিণত করুন। ব্যবসাগুলি গ্রাহকদের সাথে সংযুক্ত হয় যারা সক্রিয়ভাবে তাদের পরিষেবা খুঁজছে।' },
      costSaving: { title: 'খরচ সাশ্রয়ের সরঞ্জাম', desc: 'ইচ্ছা-ভিত্তিক মেলানোর মাধ্যমে আপনার যা প্রয়োজন তা খুঁজে অর্থ সাশ্রয় করুন। কোন ব্যয়বহুল বিজ্ঞাপন বা মধ্যস্থতাকারী ফি নেই।' },
      informative: { title: 'তথ্যপূর্ণ', desc: 'প্রতিটি ইচ্ছার উপর AI-চালিত অন্তর্দৃষ্টি। স্মার্ট ম্যাচিং, বাজার বুদ্ধিমত্তা এবং ডেটা-চালিত সুপারিশ।' },
      problemSolving: { title: 'সমস্যা সমাধান', desc: 'একটি সমস্যা আছে? একটি ইচ্ছা পোস্ট করুন এবং আমাদের AI আপনার জন্য নিখুঁত সমাধান খুঁজে দিন।' },
    },
    tagline: {
      title: 'WishPal: সব সময় আপনার সব প্রয়োজনের জন্য একমাত্র সরঞ্জাম',
      subtitle: 'আপনার ইচ্ছা, AI দ্বারা মিলানো। প্রতিবার, প্রতিটি প্রয়োজনে।',
      cta: 'এটি বিনামূল্যে, এখনই শুরু করুন',
    },
    footer: {
      description: 'আপনার ইচ্ছা, AI দ্বারা মিলানো। আমরা আপনাকে আপনার ইচ্ছা পূরণের জন্য সঠিক লোকের সাথে সংযুক্ত করি।',
      platform: 'প্ল্যাটফর্ম',
      browseWishes: 'ইচ্ছা ব্রাউজ করুন',
      joinWishMate: 'WishMate হিসেবে যোগ দিন',
      joinWishPad: 'WishPad হিসেবে যোগ দিন',
      support: 'সহায়তা',
      faq: 'সাধারণ প্রশ্ন',
      contactUs: 'যোগাযোগ করুন',
      privacyPolicy: 'গোপনীয়তা নীতি',
      legal: 'আইনি',
      termsOfService: 'পরিষেবার শর্তাবলী',
      cookiePolicy: 'কুকি নীতি',
      allRightsReserved: 'সমস্ত অধিকার সংরক্ষিত।',
    },
    daysLeft: 'বাকি {days} দিন',
    today: 'আজ',
  },
  ur: {
    name: 'اردو',
    flag: '🇵🇰',
    rtl: true,
    navbar: { home: 'ہوم', search: 'تلاش', dashboard: 'ڈیش بورڈ' },
    hero: {
      badge: 'AI سے چلنے والا خواہشات ملانے کا پلیٹ فارم',
      title: 'ایک خواہش ہے؟ WishPal اسے پورا کرتا ہے —',
      subtitle: 'AI کے ذریعے تقویت یافتہ اور 100% مفت۔ ابھی آزمائیں',
      formula: 'آپ کی خواہش + WishPal = آپ کا حل',
      cta: { free: 'یہ مفت ہے، ابھی شروع کریں', makeWish: 'خواہش کریں', explore: 'خواہشات دیکھیں' },
      search: { placeholder: 'خواہشات تلاش کریں... مثال: "گھر کی صفائی"، "ویب ڈویلپر نوکری"', button: 'تلاش' },
    },
    ticker: {
      mostSuccessful: 'اس ہفتے کی سب سے کامیاب خواہشات:',
      jobsFound: 'نوکریاں ملیں',
      productsBought: 'خریدے گئے پروڈکٹس',
      usersAdvised: 'صارفین کو مفت مشورہ',
      trending: 'ٹرینڈنگ:',
      wishesFulfilled: 'خواہشات پوری ہوئیں',
      activeWishes: 'فعال خواہشات',
      beingPosted: 'ابھی پوسٹ کی جا رہی ہیں',
    },
    stats: {
      liveNow: 'لائیو',
      wishesLive: 'لائیو خواہشات',
      closedThisWeek: 'اس ہفتے بند ہوئیں',
      beingPostedNow: 'ابھی پوسٹ کی جا رہی ہیں',
      updatingRealTime: 'ریئل ٹائم میں اپ ڈیٹ',
    },
    banner: {
      wishesLiveNow: 'لائیو خواہشات',
      closedThisWeek: 'اس ہفتے بند ہوئیں',
      jobsFound: 'نوکریاں ملیں',
      productsBought: 'پروڈکٹس خریدے گئے',
    },
    noticeBoard: {
      title: 'نوٹس بورڈ',
      viewAll: 'سب دیکھیں',
      empty: 'ابھی تک کوئی خواہش پوسٹ نہیں ہوئی۔ پہلے بنیں!',
    },
    map: {
      title: 'WishPad نقشہ',
      allCountries: 'تمام ممالک',
      matches: 'مطابقت',
      viewPage: 'صفحہ دیکھیں',
    },
    closingSoon: {
      title: 'جلد بند ہو رہا ہے',
      empty: 'کوئی خواہش جلد بند نہیں ہو رہی',
      lastDay: 'آخری دن!',
    },
    topWishpads: {
      title: 'بہترین WishPads دریافت کریں',
      subtitle: 'ان کاروباروں اور سروس فراہم کنندگان کو دریافت کریں جو دنیا بھر میں آپ کی خواہشات پوری کرنے کے لیے تیار ہیں',
      empty: 'ابھی تک کوئی WishPad رجسٹرڈ نہیں۔ پہلے بنیں!',
      register: 'WishPad کے طور پر رجسٹر کریں',
      matches: 'مطابقت',
    },
    testimonials: {
      title: 'کامیابی کی کہانیاں',
      subtitle: 'حقیقی لوگ، حقیقی نتائج — WishPal کے ذریعے',
      verified: 'تصدیق شدہ',
    },
    features: {
      title: 'ہم سب کو WishPal کی ضرورت کیوں ہے',
      subtitle: 'وہ پلیٹ فارم جو خواہشات کو مواقع سے جوڑتا ہے',
      revenue: { title: 'آمدنی پیدا کرنے والا', desc: 'خواہشات کو آمدنی میں تبدیل کریں۔ کاروبار ان گاہکوں سے جڑتے ہیں جو ان کی خدمات تلاش کر رہے ہیں۔' },
      costSaving: { title: 'بچت کا آلہ', desc: 'خواہش پر مبنی مماثلت کے ذریعے پیسے بچائیں۔ کوئی مہنگے اشتہار یا درمیانی فیس نہیں۔' },
      informative: { title: 'معلوماتی', desc: 'ہر خواہش پر AI سے چلنے والی بصیرت۔ سمارٹ میچنگ، مارکیٹ انٹیلیجنس اور ڈیٹا پر مبنی سفارشات۔' },
      problemSolving: { title: 'مسئلہ حل کرنا', desc: 'کوئی مسئلہ ہے؟ ایک خواہش پوسٹ کریں اور ہمارے AI کو آپ کے لیے بہترین حل تلاش کرنے دیں۔' },
    },
    tagline: {
      title: 'WishPal: ہر وقت آپ کی تمام ضروریات کے لیے واحد آلہ',
      subtitle: 'آپ کی خواہشات، AI کے ذریعے مماثل۔ ہر بار، ہر ضرورت۔',
      cta: 'یہ مفت ہے، ابھی شروع کریں',
    },
    footer: {
      description: 'آپ کی خواہشات، AI کے ذریعے مماثل۔ ہم آپ کو آپ کی خواہشات پوری کرنے کے لیے صحیح لوگوں سے جوڑتے ہیں۔',
      platform: 'پلیٹ فارم',
      browseWishes: 'خواہشات براؤز کریں',
      joinWishMate: 'WishMate کے طور پر شامل ہوں',
      joinWishPad: 'WishPad کے طور پر شامل ہوں',
      support: 'معاونت',
      faq: 'عمومی سوالات',
      contactUs: 'ہم سے رابطہ کریں',
      privacyPolicy: 'رازداری کی پالیسی',
      legal: 'قانونی',
      termsOfService: 'خدمات کی شرائط',
      cookiePolicy: 'کوکی پالیسی',
      allRightsReserved: 'جملہ حقوق محفوظ ہیں۔',
    },
    daysLeft: '{days} دن باقی',
    today: 'آج',
  },
  id: {
    name: 'Bahasa Indonesia',
    flag: '🇮🇩',
    navbar: { home: 'Beranda', search: 'Cari', dashboard: 'Dasbor' },
    hero: {
      badge: 'Platform Pencocokan Keinginan dengan AI',
      title: 'Punya keinginan? WishPal mewujudkannya —',
      subtitle: 'didukung AI dan 100% gratis. Coba sekarang',
      formula: 'Keinginanmu + WishPal = Solusimu',
      cta: { free: 'Gratis, mulai sekarang', makeWish: 'Buat Keinginan', explore: 'Jelajahi Keinginan' },
      search: { placeholder: 'Cari keinginan... cth: "bersihkan rumah", "pekerjaan developer web"', button: 'Cari' },
    },
    ticker: {
      mostSuccessful: 'Keinginan paling sukses minggu ini:',
      jobsFound: 'Pekerjaan ditemukan',
      productsBought: 'Produk dibeli',
      usersAdvised: 'Pengguna diberi saran gratis',
      trending: 'Tren:',
      wishesFulfilled: 'Keinginan terpenuhi',
      activeWishes: 'Keinginan aktif',
      beingPosted: 'Sedang diposting sekarang',
    },
    stats: {
      liveNow: 'Langsung',
      wishesLive: 'Keinginan Langsung',
      closedThisWeek: 'Ditutup Minggu Ini',
      beingPostedNow: 'Sedang Diposting Sekarang',
      updatingRealTime: 'Diperbarui secara real-time',
    },
    banner: {
      wishesLiveNow: 'Keinginan Langsung',
      closedThisWeek: 'Ditutup Minggu Ini',
      jobsFound: 'Pekerjaan Ditemukan',
      productsBought: 'Produk Dibeli',
    },
    noticeBoard: {
      title: 'Papan Pengumuman',
      viewAll: 'Lihat semua',
      empty: 'Belum ada keinginan yang diposting. Jadilah yang pertama!',
    },
    map: {
      title: 'Peta WishPad',
      allCountries: 'Semua Negara',
      matches: 'cocok',
      viewPage: 'Lihat Halaman',
    },
    closingSoon: {
      title: 'Segera Ditutup',
      empty: 'Tidak ada keinginan yang segera ditutup',
      lastDay: 'Hari terakhir!',
    },
    topWishpads: {
      title: 'Jelajahi WishPads Teratas',
      subtitle: 'Temukan bisnis dan penyedia layanan yang siap mewujudkan keinginan Anda di seluruh dunia',
      empty: 'Belum ada WishPad yang terdaftar. Jadilah yang pertama!',
      register: 'Daftar sebagai WishPad',
      matches: 'cocok',
    },
    testimonials: {
      title: 'Kisah Sukses',
      subtitle: 'Orang nyata, hasil nyata — didukung oleh WishPal',
      verified: 'Terverifikasi',
    },
    features: {
      title: 'Mengapa Kita Semua Membutuhkan WishPal',
      subtitle: 'Platform yang menghubungkan keinginan dengan peluang',
      revenue: { title: 'Penghasil Pendapatan', desc: 'Ubah keinginan menjadi pendapatan. Bisnis terhubung dengan pelanggan yang secara aktif mencari layanan mereka.' },
      costSaving: { title: 'Alat Penghemat Biaya', desc: 'Hemat uang dengan menemukan apa yang Anda butuhkan melalui pencocokan berbasis keinginan. Tanpa iklan mahal atau biaya perantara.' },
      informative: { title: 'Informatif', desc: 'Wawasan berbasis AI untuk setiap keinginan. Pencocokan cerdas, intelijen pasar, dan rekomendasi berbasis data.' },
      problemSolving: { title: 'Pemecahan Masalah', desc: 'Punya masalah? Posting keinginan dan biarkan AI kami menemukan solusi sempurna untuk Anda.' },
    },
    tagline: {
      title: 'WishPal: Satu-satunya alat untuk semua kebutuhan Anda setiap saat',
      subtitle: 'Keinginan Anda, dicocokkan oleh AI. Setiap saat, setiap kebutuhan.',
      cta: 'Gratis, mulai sekarang',
    },
    footer: {
      description: 'Keinginan Anda, dicocokkan oleh AI. Kami menghubungkan Anda dengan orang yang tepat untuk mewujudkan keinginan Anda.',
      platform: 'Platform',
      browseWishes: 'Jelajahi Keinginan',
      joinWishMate: 'Bergabung sebagai WishMate',
      joinWishPad: 'Bergabung sebagai WishPad',
      support: 'Dukungan',
      faq: 'FAQ',
      contactUs: 'Hubungi Kami',
      privacyPolicy: 'Kebijakan Privasi',
      legal: 'Hukum',
      termsOfService: 'Ketentuan Layanan',
      cookiePolicy: 'Kebijakan Cookie',
      allRightsReserved: 'Semua hak dilindungi.',
    },
    daysLeft: '{days} hari lagi',
    today: 'Hari ini',
  },
  ja: {
    name: '日本語',
    flag: '🇯🇵',
    navbar: { home: 'ホーム', search: '検索', dashboard: 'ダッシュボード' },
    hero: {
      badge: 'AI搭載ウィッシュマッチングプラットフォーム',
      title: '願い事はありますか？WishPalが実現します —',
      subtitle: 'AI搭載、100%無料。今すぐ試す',
      formula: 'あなたの願い + WishPal = あなたの解決策',
      cta: { free: '無料です、今すぐ始める', makeWish: '願い事をする', explore: '願い事を探す' },
      search: { placeholder: '願い事を検索... 例：「家の掃除」「ウェブ開発者の仕事」', button: '検索' },
    },
    ticker: {
      mostSuccessful: '今週の最も成功した願い事:',
      jobsFound: '見つかった仕事',
      productsBought: '購入された商品',
      usersAdvised: '無料でアドバイスを受けたユーザー',
      trending: 'トレンド:',
      wishesFulfilled: '叶った願い事',
      activeWishes: 'アクティブな願い事',
      beingPosted: '投稿されているもの',
    },
    stats: {
      liveNow: 'ライブ',
      wishesLive: 'ライブの願い事',
      closedThisWeek: '今週クローズ',
      beingPostedNow: '投稿されています',
      updatingRealTime: 'リアルタイムで更新中',
    },
    banner: {
      wishesLiveNow: 'ライブの願い事',
      closedThisWeek: '今週クローズ',
      jobsFound: '見つかった仕事',
      productsBought: '購入された商品',
    },
    noticeBoard: {
      title: '掲示板',
      viewAll: 'すべて見る',
      empty: 'まだ願い事は投稿されていません。最初になりましょう！',
    },
    map: {
      title: 'WishPadマップ',
      allCountries: 'すべての国',
      matches: 'マッチ',
      viewPage: 'ページを見る',
    },
    closingSoon: {
      title: '間もなく終了',
      empty: '間もなく終了する願い事はありません',
      lastDay: '最終日！',
    },
    topWishpads: {
      title: 'トップWishPadを探索',
      subtitle: '世界中であなたの願いを叶える準備ができている企業やサービスプロバイダーを見つけましょう',
      empty: 'まだWishPadは登録されていません。最初になりましょう！',
      register: 'WishPadとして登録',
      matches: 'マッチ',
    },
    testimonials: {
      title: '成功事例',
      subtitle: '実際の人々、実際の結果 — WishPalが実現',
      verified: '確認済み',
    },
    features: {
      title: 'なぜ私たち全員にWishPalが必要なのか',
      subtitle: '願いと機会をつなぐプラットフォーム',
      revenue: { title: '収益ジェネレーター', desc: '願い事を収益に変えます。企業は自社のサービスを積極的に探している顧客とマッチングします。' },
      costSaving: { title: 'コスト削減ツール', desc: '願い事ベースのマッチングで必要なものを正確に見つけてお金を節約。高額な広告や仲介手数料は不要です。' },
      informative: { title: '情報豊富', desc: 'すべての願い事に対するAI搭載のインサイト。スマートマッチング、マーケットインテリジェンス、データ駆動型レコメンデーション。' },
      problemSolving: { title: '問題解決', desc: '問題がありますか？願い事を投稿して、AIが最適な解決策を見つけます。' },
    },
    tagline: {
      title: 'WishPal: あらゆるニーズに応えるたった一つのツール',
      subtitle: 'あなたの願い事、AIがマッチング。毎回、あらゆるニーズに。',
      cta: '無料です、今すぐ始める',
    },
    footer: {
      description: 'あなたの願い事、AIがマッチング。あなたの願いを叶える適切な人とつなぎます。',
      platform: 'プラットフォーム',
      browseWishes: '願い事を閲覧',
      joinWishMate: 'WishMateとして参加',
      joinWishPad: 'WishPadとして参加',
      support: 'サポート',
      faq: 'よくある質問',
      contactUs: 'お問い合わせ',
      privacyPolicy: 'プライバシーポリシー',
      legal: '法的情報',
      termsOfService: '利用規約',
      cookiePolicy: 'クッキーポリシー',
      allRightsReserved: '全著作権所有。',
    },
    daysLeft: '残り{days}日',
    today: '今日',
  },
  ha: {
    name: 'Hausa',
    flag: '🇳🇬',
    navbar: { home: 'Gida', search: 'Bincike', dashboard: 'Dashboard' },
    hero: {
      badge: 'Dandalin Daidaita Buri da AI',
      title: 'Kana da buri? WishPal ta cika shi —',
      subtitle: 'AI ke tafiyar da shi kuma kyauta 100%. Gwada yanzu',
      formula: 'Burinka + WishPal = Maganinka',
      cta: { free: 'Kyauta ne, fara yanzu', makeWish: 'Yi Buri', explore: 'Bincika Burori' },
      search: { placeholder: 'Bincika burori... mis: "tsaftace gida", "aikin mai yanar gizo"', button: 'Bincika' },
    },
    ticker: {
      mostSuccessful: 'Burori mafi nasara a wannan satin:',
      jobsFound: 'Ayyuka da aka samu',
      productsBought: 'Kayayyakin da aka saya',
      usersAdvised: 'Masu amfani da aka ba da shawara kyauta',
      trending: 'Mashahuri:',
      wishesFulfilled: 'Burori da aka cika',
      activeWishes: 'Burori masu aiki',
      beingPosted: 'Ana aikawa yanzu',
    },
    stats: {
      liveNow: 'Kai Tsaye',
      wishesLive: 'Burori Kai Tsaye',
      closedThisWeek: 'An Rufe Wannan Sat',
      beingPostedNow: 'Ana Aikawa Yanzu',
      updatingRealTime: 'Ana sabuntawa a lokaci gaskiya',
    },
    banner: {
      wishesLiveNow: 'Burori Kai Tsaye',
      closedThisWeek: 'An Rufe Wannan Sat',
      jobsFound: 'Ayyukan da aka Samu',
      productsBought: 'Kayayyakin da aka Saya',
    },
    noticeBoard: {
      title: 'Allon Sanarwa',
      viewAll: 'Duba duka',
      empty: 'Babu burori da aka aiko tukuna. Ka zama na farko!',
    },
    map: {
      title: 'Taswirar WishPad',
      allCountries: 'Duk Kasashe',
      matches: 'daidaitawa',
      viewPage: 'Duba Shafi',
    },
    closingSoon: {
      title: 'Rufewa da Jim Kadan',
      empty: 'Babu burori da ke rufewa da jim kadan',
      lastDay: 'Rana ta Karshe!',
    },
    topWishpads: {
      title: 'Bincika Manyan WishPads',
      subtitle: 'Gano kasuwanci da masu samar da sabis a shirye suke don cika burorinka a duk duniya',
      empty: 'Babu WishPads da aka yi rajista tukuna. Ka zama na farko!',
      register: 'Yi Rajista a matsayin WishPad',
      matches: 'daidaitawa',
    },
    testimonials: {
      title: 'Labarun Nasara',
      subtitle: 'Mutane na gaske, sakamako na gaske — WishPal ke tafiyar da shi',
      verified: 'An Tabbatar',
    },
    features: {
      title: 'Dalilin Da Yasa Dukanmu Muke Bukatar WishPal',
      subtitle: 'Dandalin da ke haɗa burori da dama',
      revenue: { title: 'Mai Samar da Kuɗi', desc: 'Mayar da burori zuwa kuɗi. Kasuwanci suna haɗuwa da abokan ciniki masu neman ayyukansu.' },
      costSaving: { title: 'Kayan Aiki na Ajiye Kuɗi', desc: 'Ajiye kuɗi ta hanyar samun ainihin abin da kake bukata. Babu tallace-tallace masu tsada ko kuɗin dillali.' },
      informative: { title: 'Bayani', desc: 'Fahimtar AI akan kowane buri. Daidaitawa mai wayo da shawarwarin da data ke tafiyar da su.' },
      problemSolving: { title: 'Magance Matsala', desc: 'Kana da matsala? Saka buri ka bar AI ta nemo maka mafita mafi dacewa.' },
    },
    tagline: {
      title: 'WishPal: Kayan aiki daya tilo ga duk bukatunka a kowane lokaci',
      subtitle: 'Burorinka, AI ta daidaita su. Kowane lokaci, kowace bukata.',
      cta: 'Kyauta ne, fara yanzu',
    },
    footer: {
      description: 'Burorinka, AI ta daidaita su. Muna haɗa ka da mutanen da suka dace don cika burorinka.',
      platform: 'Dandali',
      browseWishes: 'Bincika Burori',
      joinWishMate: 'Shiga a matsayin WishMate',
      joinWishPad: 'Shiga a matsayin WishPad',
      support: 'Taimako',
      faq: 'Tambayoyi',
      contactUs: 'Tuntube Mu',
      privacyPolicy: 'Manufar Sirri',
      legal: 'Doka',
      termsOfService: 'Sharuɗɗan Sabis',
      cookiePolicy: 'Manufar Kuki',
      allRightsReserved: 'Duk haƙƙoƙi an kiyaye su.',
    },
    daysLeft: 'sauran {days} kwanaki',
    today: 'Yau',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem('wishpal-lang') || 'en';
    } catch { return 'en'; }
  });

  useEffect(() => {
    try { localStorage.setItem('wishpal-lang', language); } catch {}
    const dir = translations[language]?.rtl ? 'rtl' : 'ltr';
    document.documentElement.setAttribute('dir', dir);
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = useCallback((key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        // Fallback to English
        let fallback = translations.en;
        for (const fk of keys) {
          fallback = fallback?.[fk];
        }
        return fallback ?? key;
      }
    }
    return typeof value === 'string' ? value : key;
  }, [language]);

  const tReplace = useCallback((key, replacements) => {
    let text = t(key);
    for (const [placeholder, value] of Object.entries(replacements)) {
      text = text.replace(`{${placeholder}}`, value);
    }
    return text;
  }, [t]);

  const languageOptions = Object.entries(translations).map(([code, lang]) => ({
    code,
    name: lang.name,
    flag: lang.flag,
  }));

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tReplace, languageOptions }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export { translations };
